### ISSUE TITLE
Not accepted in Hacktoberfest 2022

### ISSUE THREAD

**Issue by umadhatri** [maheshjainckd/Hacktoberfest2022-for-everyone#375]
It says that the repo is not accepted for Hacktoberfest 2022. Is it the repo or my PR? Please let me know which issue is it
![Screen Shot 2022-10-01 at 2 32 00 PM](https://user-images.githubusercontent.com/97341880/193401902-97684d9d-7938-444e-b5df-0e711c0c4e44.png)

**Comment by maheshjainckd** [comment]
It is showing because your pull request is not reviewed by any of moderators till now. Once your pull request is approved with hacktoberfest-accepted then it will update.

**Comment by umadhatri** [comment]
Thank you

**Comment by ItzLevvie** [comment]
This repository has been **_permanently_** excluded from Hacktoberfest 2022. This means that any pull requests (PRs) made to this repository **_will_** not be counted towards your contributions for Hacktoberfest 2022.

Please contribute to **_valuable_** repositories instead of sending pull requests (PRs) to repositories that are there to defeat the whole purpose of Hacktoberfest 2022.

Any repeated, continuous exclusions will automatically ban your account from participating in Hacktoberfest 2022.
