### ISSUE TITLE
This repo is excluded from Hacktoberfest

### ISSUE THREAD

**Issue by AvidCoder101** [maheshjainckd/Hacktoberfest2022-for-everyone#446]
![image](https://user-images.githubusercontent.com/70807684/193409450-a24bd598-07e5-44ea-b9ad-11006ac09252.png)
 

Looks like the repo is excluded. I would make contributors aware :)

**Comment by AD1TYA03** [comment]
Thanks

**Comment by ItzLevvie** [comment]
This repository has been **_permanently_** excluded from Hacktoberfest 2022. This means that any pull requests (PRs) made to this repository **_will_** not be counted towards your contributions for Hacktoberfest 2022.

Please contribute to **_valuable_** repositories instead of sending pull requests (PRs) to repositories that are there to defeat the whole purpose of Hacktoberfest 2022.

Any repeated, continuous exclusions will automatically ban your account from participating in Hacktoberfest 2022.

**Comment by Meghwantsingh** [comment]
> This repository has been **_permanently_** excluded from Hacktoberfest 2022. This means that any pull requests (PRs) made to this repository **_will_** not be counted towards your contributions for Hacktoberfest 2022.
> 
> Please contribute to **_valuable_** repositories instead of sending pull requests (PRs) to repositories that are there to defeat the whole purpose of Hacktoberfest 2022.
> 
> Any repeated, continuous exclusions will automatically ban your account from participating in Hacktoberfest 2022.

I am following all rules of hacktoberfest 2022 but still my repo is excluded? 
So, what exactly should new maintainers do !
